### ISSUE TITLE
因為 driver.quit() 在 finally 裡，所以程式因 exception 中斷時 driver 已經被關掉了，干擾到我們的 debug...

### ISSUE THREAD

**Issue by yuttai** [yuttai/Special-course-for-big-data-on-education#3]
@Jerry263104 我記得你昨天下午來找我時，我們已經處理了這一段，可以麻煩你先幫這段程式加註解，接著 commit & push 這段程式，之後再開始改其他的部份嗎？這樣我才有辦法試試看用新的程式會不會比較好 debug... 謝啦～～

**Comment by Jerry263104** [comment]
老師我剛剛push上去了，如果有什麼問題再告知我

**Comment by yuttai** [comment]
我看到了，謝啦～～
